name: Deploy API Gateway

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::048834124872:role/GitHubActionsApiGatewayRole
          aws-region: us-east=1

      - name: Validate CloudFormation
        run: |
          aws cloudformation validate-template \
            --template-body file://cloudformation/api-gateway.yaml

      - name: Deploy API Gateway
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/api-gateway.yaml \
            --stack-name my-api-gateway-dev \
            --parameter-overrides \
              LambdaFunctionArn=arn:aws:lambda:us-east-1::runtime:3f2695d917b249350567df30dd784ee6b9547bbdb635b4c188153c39b5347c8b \
              CognitoUserPoolId= \
              CognitoAppClientId=4lcp7epkr196tgh9d5ml4esrm5 \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
